#!/bin/bash
set -euo pipefail

DOC="Harthong - Probabilités et Statistiques"
CHAPTERS=(chap{01..14})
# 'index' should be added just before 'bibliog', 
#  but so far I can't build it (missing file). 
SRC="avert ${CHAPTERS[*]} bibliog"
SRC_ARRAY=($SRC) 
PDF="${SRC_ARRAY[@]/%/.pdf}"

pushd .

cd tex
for src in $SRC; do
  tex $src.tex && dvipdf $src.dvi
done
pdftk $PDF cat output "$DOC.pdf"
cp "$DOC.pdf" ..

popd

